version: "3.9"
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DB}
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
