"""add price

Revision ID: 0e381ad812b2
Revises: d2020b0f1630
Create Date: 2022-09-30 14:21:11.672160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e381ad812b2'
down_revision = 'd2020b0f1630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
